name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate snake SVGs
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push generated files to output branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan output || git checkout output
          rm -rf ./* .gitignore .github
          cp -r /home/runner/work/CarlosEduardoLemos/CarlosEduardoLemos/dist/* .
          git add .
          git commit -m "Update contribution snake" || exit 0
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
