name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate snake SVGs
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        run: |
          cd dist
          git init
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Generate snake contribution grid"
          git branch -M output
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -u origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
